# Generated by Django 4.1.1 on 2023-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название картридж')),
                ('foruseonaprinter', models.CharField(max_length=255, verbose_name='Для использования на принтере')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Модель картридж')),
            ],
            options={
                'verbose_name': 'Модель картридж',
                'verbose_name_plural': 'Модель картридж',
            },
        ),
        migrations.CreateModel(
            name='TransferCartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Передать картридж',
                'verbose_name_plural': 'Передать картридж',
            },
        ),
    ]
