# Generated by Django 4.1.1 on 2023-03-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('cartridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercartridge',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_key', to='main.campus', verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='transfercartridge',
            name='cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridge_key', to='cartridge.cartridge', verbose_name='Название картридж'),
        ),
        migrations.AddField(
            model_name='transfercartridge',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_key', to='main.faculty', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='transfercartridge',
            name='kabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabinet_key', to='main.kabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='transfercartridge',
            name='namKabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namKabinet_key', to='main.namkabinet', verbose_name='Название кабинета'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_key', to='cartridge.model', verbose_name='Модель картридж'),
        ),
    ]
