# Generated by Django 4.1.1 on 2023-03-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, max_length=250, null=True, upload_to='document/', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'документы',
                'verbose_name_plural': 'документы',
            },
        ),
    ]
