# Generated by Django 4.1.1 on 2023-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_documentation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документ'),
        ),
    ]
