# Generated by Django 4.1.1 on 2023-03-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('Edizm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_key', to='main.edizm', verbose_name='ЕдИзм')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_key', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рапорт на подразделение')),
                ('document', models.FileField(blank=True, max_length=250, null=True, upload_to='document/', verbose_name='Рапорт')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сделано')),
                ('no_report', models.BooleanField(default=False, verbose_name='Без рапорт')),
            ],
            options={
                'verbose_name': 'Списание по рапорту',
                'verbose_name_plural': 'Списание по рапорту',
            },
        ),
        migrations.CreateModel(
            name='Transfernetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='network.report', verbose_name='Рапорт')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.faculty', verbose_name='Подразделение')),
                ('kabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.kabinet', verbose_name='Кабинет')),
                ('namKabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.namkabinet', verbose_name='Название кабинета')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='network.network', verbose_name='Наименование материала')),
            ],
            options={
                'verbose_name': 'Добавить материал',
                'verbose_name_plural': 'Добавить материал',
            },
        ),
    ]
