# Generated by Django 4.1.1 on 2023-03-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('network', '0002_transfernetwork_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfernetwork',
            name='campus',
        ),
        migrations.AddField(
            model_name='report',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txst_key1', to='main.campus', verbose_name='Корпус'),
        ),
    ]
