# Generated by Django 4.1.1 on 2023-03-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('network', '0003_remove_transfernetwork_campus_report_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfernetwork',
            name='faculty',
        ),
        migrations.AddField(
            model_name='report',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.faculty', verbose_name='Подразделение'),
        ),
    ]
