# Generated by Django 4.1.1 on 2023-03-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('network', '0005_remove_report_reportitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfernetwork',
            name='namKabinet',
        ),
        migrations.AddField(
            model_name='report',
            name='namKabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.namkabinet', verbose_name='Название кабинета'),
        ),
    ]
