# Generated by Django 4.1.1 on 2023-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NalichiTehniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodTMU', models.IntegerField(verbose_name='КодТМУ')),
                ('Naimenovanie', models.CharField(max_length=255, null=True, verbose_name='Наименования')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('sostoyanie', models.CharField(choices=[('рабочий', 'рабочий'), ('не рабочий', 'не рабочий')], max_length=20, null=True, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Наличие техники',
                'verbose_name_plural': 'Наличие техники',
            },
        ),
    ]
