# Generated by Django 4.1.1 on 2023-03-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingener1', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalichitehniki',
            name='Campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txst_key', to='main.campus', verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='Edizm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_key', to='main.edizm', verbose_name='ЕдИзм'),
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_key', to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='kabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txst_key', to='main.kabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='namKabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txst_key', to='main.namkabinet', verbose_name='Название кабинета'),
        ),
    ]
