# Generated by Django 4.1.1 on 2023-03-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingener1', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nalichitehniki',
            name='namKabinet',
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
