# Generated by Django 4.1.1 on 2023-04-07 15:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userrole_campus'),
        ('ingener1', '0004_alter_nalichitehniki_kabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalichitehniki',
            name='kabinet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='Campus', chained_model_field='campus', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kabinet', verbose_name='Кабинет'),
        ),
    ]
