# Generated by Django 4.1.1 on 2023-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingener1', '0007_alter_nalichitehniki_kodtmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalichitehniki',
            name='kodTMU',
            field=models.CharField(max_length=200, verbose_name='КодТМУ'),
        ),
    ]
