# Generated by Django 4.1.1 on 2023-03-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название заявка')),
                ('document', models.FileField(blank=True, max_length=250, null=True, upload_to='document/', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Заявка на тендер',
                'verbose_name_plural': 'Заявка на тендер',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название заявка')),
                ('document', models.FileField(blank=True, max_length=250, null=True, upload_to='document/', verbose_name='Документы')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_key1', to='main.faculty', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявка',
            },
        ),
    ]
