# Generated by Django 4.1.1 on 2023-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_application',
            field=models.BooleanField(default=False, verbose_name='Принял заявка'),
        ),
        migrations.AddField(
            model_name='application',
            name='no_report',
            field=models.BooleanField(default=False, verbose_name='Без рапорт'),
        ),
    ]
