# Generated by Django 4.1.1 on 2023-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_accepted_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='purchase_order_is_ready',
            field=models.BooleanField(default=False, verbose_name='Заявка на закупку готова'),
        ),
    ]
