# Generated by Django 4.1.1 on 2023-03-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='campus',
            field=models.ManyToManyField(related_name='user_role_campus_key', to='main.campus'),
        ),
    ]
