# Generated by Django 4.1.1 on 2023-04-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userrole_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabinet',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txst_key11', to='main.campus', verbose_name='Корпус'),
        ),
    ]
